version: '3.9'

networks:
  rpg-internal:
    internal: true

services:
  server:
    build:
      context: .        # racine du repo = shared/ accessible
      dockerfile: server/Dockerfile
    networks:
      - rpg-internal
    environment:
      - NODE_ENV=production
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
    restart: unless-stopped

  client:
    build:
      context: .        # racine du repo = shared/ accessible
      dockerfile: client/Dockerfile
      args:
        - VITE_SERVER_URL=${CLIENT_ORIGIN}
    networks:
      - rpg-internal
    depends_on:
      - server
    restart: unless-stopped
